### ISSUE TITLE
Installing with a package manager

### ISSUE THREAD

**Issue by juanibiapina** [ztombol/bats-docs#1]
I would like to gather some thoughts on how to make these libraries (and any other dev libs) easily installable with basher.

Suppose I add a new command to basher:

```
$ basher dev-bundle
```

This would look for a `package.sh` file on the current directory, look for an item DEV_DEPENDENCIES, and install each dependency on a local path (instead of the global basher cellar). These dependencies could then be loaded with a simple change to the `load` command that you're already suggesting.

In the future, maybe basher itself could provide a way to load all dev dependencies automatically.

This is just an initial idea from the top of my head. If you like it, I would like your thoughts on how to evolve it.

**Comment by juanibiapina** [comment]
After a night's sleep I came up with an alternative:

Add a command `basher bundle` that globally installs all dependencies of the current project. Then, basher could provide a command similar to "load" that knows how to load libraries into the current shell, for instance:

```
basher-load ztombol/bats-core
basher-load ztombol/bats-assert
```

I think I like this option better.

**Comment by ztombol** [comment]
More installation methods! This would be great! Though, I'm not familiar with basher. I've got a few things to finish first (e.g. travis ci, examples), but I'll look into this as soon as I can. Let's see what others have to say. Though, since you are the developer of basher, I'm sure you know what you are doing. :smile:

**Comment by jasonkarns** [comment]
I don't want to hijack this thread, but I'll point out that the nodenv org has a vested interest in bats-\* being installable via npm (not necessarily from the registry, just using an npm-compatible package.json file; potentially even shared by bpkg)

**Comment by jasonkarns** [comment]
What's the status of this @juanibiapina ? Something PR-able to the readme, perhaps?

**Comment by juanibiapina** [comment]
`basher` currently has an `include` command which sources a file from a package into the current shell. It's very explicit and bare bones, but it solved my use case: https://github.com/basherpm/basher/blob/master/lib/include.sh

`basher` itself uses `load` from `bats`. I have no easy way to change that because then I would make `basher` depend on itself in order to run its own tests. Since I have worked on almost nothing else in bash these days, I haven't had again the need for a `bundle` command.

This can be closed, if no one else is interested.

**Comment by jasonkarns** [comment]
Would you be interested in opening a PR to the readme that just adds an example for how to install/load the bats-support/bats-assert libs using basher? I wouldn't mind merging an addition like that to my fork of bats-docs: https://github.com/jasonkarns/bats-docs

**Comment by juanibiapina** [comment]
This might be a good idea. I'm having trouble finding time these two weeks but will do so soon.
