### ISSUE TITLE
Warning about unmet peer dependency what using npm

### ISSUE THREAD

**Issue by mbigras** [ztombol/bats-docs#12]
Hi ztombol,

Thanks for your work on this project! I've been trying to use `npm` as specified in the [installation](https://github.com/ztombol/bats-docs#npm) section. But I'm getting a `UNMET PEER DEPENDENCY` error.

Please let me know if there any other info I can give you to help :D

```
$ ls
package.json
$ cat package.json
{
  "name": "hello-bats-assert",
  "version": "1.0.0",
  "description": "Testing bats-assert",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "repository": {
    "type": "git",
    "url": "private"
  },
  "author": "Max Bigras",
  "license": "CC0-1.0"
}
$ npm install --save-dev https://github.com/ztombol/bats-support
hello-bats-assert@1.0.0 /Users/max/Dropbox/work/src/github.com/mbigras/hello-bats-assert
└── bats-support@0.2.0  (git+https://github.com/ztombol/bats-support.git#d0a131831c487a1f1141e76d3ab386c89642cdff)

$ npm install --save-dev https://github.com/ztombol/bats-assert
hello-bats-assert@1.0.0 /Users/max/Dropbox/work/src/github.com/mbigras/hello-bats-assert
├── bats-assert@0.3.0  (git+https://github.com/ztombol/bats-assert.git#9f88b4207da750093baabc4e3f41bf68f0dd3630)
└── UNMET PEER DEPENDENCY bats-support@0.2.0 (git+https://github.com/ztombol/bats-support.git#d0a131831c487a1f1141e76d3ab386c89642cdff)

npm WARN bats-assert@0.3.0 requires a peer of bats-support@git+https://github.com/ztombol/bats-support.git#v0.2.0 but none was installed.
$
$ tree -L 2 .
.
├── node_modules
│   ├── bats-assert
│   └── bats-support
└── package.json

3 directories, 1 file
$  npm --version
3.10.9
$  npm i
npm WARN bats-assert@0.3.0 requires a peer of bats-support@git+https://github.com/ztombol/bats-support.git#v0.2.0 but none was installed.
```

**Comment by ztombol** [comment]
Hi @mbigras! Thanks for reporting this problem!
@jasonkarns Can you comment on this, please?

**Comment by jasonkarns** [comment]
npm doesn't see that `bats-support@git+https://github.com/ztombol/bats-support.git#v0.2.0` and `https://github.com/ztombol/bats-support` refer to the same package. So it doesn't realise that bats-support is already installed.

But it's only a warning. It doesn't impact actual use in any way. Indeed, once bats-assert and bats-support are published to npm, then we can update the peerDeps to refer to the packages on npm, and the warning will go away.

**Comment by mbigras** [comment]
Hi @ztombol and @jasonkarns! Okay sounds good, thanks for getting back to me.

**Comment by jasonkarns** [comment]
@mbigras sure! Also, we have a ticket for [publishing to npm](https://github.com/ztombol/bats-assert/issues/8) if you're interested in keeping an eye on that.
