### ISSUE TITLE
mocking/stubbing/spying lib

### ISSUE THREAD

**Issue by jasonkarns** [ztombol/bats-docs#4]
Thoughts on creating a mocking/stubbing/spying lib to go here?

I extracted [bats-mock](https://github.com/jasonkarns/bats-mock) from ruby-build, but I'd love to see one created here and improved. (Especially one that properly distinguishes between mocks, stubs, and spies.)

**Comment by kaos** [comment]
I've added `bats-mock` to my brew tap `kaos/shell`.. ;)
